defmodule Challenge.Schema do
  @moduledoc """
  Module that can be used by ecto schema modules to adopt 
  a shared set of appropriate defaults.
  """

  defmacro __using__(_) do
    quote do
      use Ecto.Schema
      # Use an autogenerated binary id primary key
      @primary_key {:id, :binary_id, autogenerate: true}

      # Timestamps will typically be UTC datetime
      @timestamps_opts [type: :utc_datetime]
    end
  end
end
